<a href="https://colab.research.google.com/github/craig-shenton/AU-mockup.github.io/blob/main/dev/package.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# nhspy-plotthedots

In [17]:
%pip install --index-url https://test.pypi.org/simple/ --no-deps nhspy-plotthedots-test

import pandas as pd

Looking in indexes: https://test.pypi.org/simple/, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nhspy-plotthedots-test in /usr/local/lib/python3.8/dist-packages (0.1.6)

In [18]:
# File path of the CSV file
url = 'https://raw.githubusercontent.com/nhs-pycom/nhspy-plotthedots/main/nhspy_plotthedots/data/ae_attendances.csv'

# Read the CSV file and store it in a DataFrame
df = pd.read_csv(url)

df

from datetime import datetime

# Convert 'period' column to datetime format
df['period'] = pd.to_datetime(df['period'])

# Create a subset of the DataFrame based on certain conditions
sub_set = df[(df['org_code'] == "RQM") & (df['type'] == "1") & (df['period'] < datetime(2018, 4, 1))]
sub_set = sub_set.sort_values(by='period').reset_index(drop=True)

sub_set

       period org_code type  attendances  breaches  admissions
0  2016-04-01      RQM    1        15154      1199        3415
1  2016-05-01      RQM    1        16705       929        3590
2  2016-06-01      RQM    1        16021       970        3398
3  2016-07-01      RQM    1        16761      1178        3321
4  2016-08-01      RQM    1        15084      1110        3198
5  2016-09-01      RQM    1        15918      1388        3260
6  2016-10-01      RQM    1        16564      2061        3563
7  2016-11-01      RQM    1        16478      1985        3399
8  2016-12-01      RQM    1        16931      2675        3671
9  2017-01-01      RQM    1        16920      3141        3339
10 2017-02-01      RQM    1        14482      1942        3188
11 2017-03-01      RQM    1        17414      2030        3597
12 2017-04-01      RQM    1        15957      1309        3375
13 2017-05-01      RQM    1        17871      1960        3825
14 2017-06-01      RQM    1        16675      1169        3542
15 2017-07-01      RQM    1        17265      1117        3610
16 2017-08-01      RQM    1        15872      1085        3529
17 2017-09-01      RQM    1        16776      1492        3680
18 2017-10-01      RQM    1        18024      1280        3829
19 2017-11-01      RQM    1        17891      1197        3618
20 2017-12-01      RQM    1        17695      1569        3729
21 2018-01-01      RQM    1        17990      1406        3893
22 2018-02-01      RQM    1        16205      1328        3436
23 2018-03-01      RQM    1        18906      1564        3899

In [19]:
from nhspy_plotthedots import pandas_spc_calculations

spc = pandas_spc_calculations.pandas_spc_x_calc(sub_set, 'breaches')
spc.head()

,period,org_code,type,attendances,breaches,admissions,mean,lpl,upl,outside_limits,relative_to_mean,close_to_limits,special_cause_flag
0,2016-04-01,RQM,1,15154,1199,3415,1545.166667,740.395758,2349.937576,False,-1.0,False,False
1,2016-05-01,RQM,1,16705,929,3590,1545.166667,740.395758,2349.937576,False,-1.0,True,True
2,2016-06-01,RQM,1,16021,970,3398,1545.166667,740.395758,2349.937576,False,-1.0,True,True
3,2016-07-01,RQM,1,16761,1178,3321,1545.166667,740.395758,2349.937576,False,-1.0,False,False
4,2016-08-01,RQM,1,15084,1110,3198,1545.166667,740.395758,2349.937576,False,-1.0,False,False

In [20]:
from nhspy_plotthedots import plotly_spc_chart

plotly_spc_chart.plotly_spc_chart(spc, 'breaches', 'period', plot_title = 'Chelsea & Westminster Hospital NHS Foundation Trust (RQM)', x_lab = 'Month of attendance', y_lab = 'Number of 4-Hour Target Breaches')